apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e5l6u8i2s-python
  janus-idp.io/tekton: e5l6u8i2s-python
  backstage.io/kubernetes-id: e5l6u8i2s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e5l6u8i2s-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
