apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: e5l6u8i2s-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e5l6u8i2s-python 
  name: e5l6u8i2s-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: e5l6u8i2s-python
    weight: 100 
