apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e5l6u8i2s-python-gitops
  description: This is GitOps manifest for e5l6u8i2s-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: e5l6u8i2s-python
    janus-idp.io/tekton: e5l6u8i2s-python 
    backstage.io/kubernetes-id: e5l6u8i2s-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e5l6u8i2s-python
